##########################################################
##################  所有profile共有的配置  #################
##########################################################
###################  spring配置  ###################
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

  ###################  mybatis-plus配置  ###################
  mybatis-plus:
    mapper-locations: classpath*:com/jpfss/guns/**/mapping/*.xml
    typeAliasesPackage: com.stylefeng.guns.common.persistence.model
    global-config:
      id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
      db-column-underline: false
      refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: false
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

